# Generated by Django 4.1.4 on 2023-01-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='picture',
            field=models.CharField(max_length=250),
        ),
    ]
